<a href="https://colab.research.google.com/github/Farzinaayub/sem2nbeyond/blob/colab/tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array
print(a)

<built-in function array>


In [8]:
from numpy.core.getlimits import array
import numpy
a = numpy.array([1,2,3])
print("a:")
print(a)
print(type(a))
#multidimensional array
b = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print("b:")
print(b)

a:
[1 2 3]
<class 'numpy.ndarray'>
b:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#complex number array
import numpy
a = numpy.array([[1,2,3],[4,5,6]],dtype=complex)
print(a)
print(type(a))
#to find dimension of array
print(a.ndim)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
<class 'numpy.ndarray'>
2


In [27]:
#size
arr = numpy.array([[1,8,9]])
print("size:",arr.itemsize,"bytes")
#element datatype
print(arr.dtype)
print("array size:",arr.size)
print("array shape:",arr.shape)

size: 8 bytes
int64
array size: 3
array shape: (1, 3)


In [35]:
a = numpy.array([[1,2],[4,5],[7,8]])
print("original array:")
print(a)
print("shape of original array:",a.shape)
a = a.reshape(2,3)
print("reshaped array (2,3):")
print(a)

original array:
[[1 2]
 [4 5]
 [7 8]]
shape of original array: (3, 2)
reshaped array (2,3):
[[1 2 4]
 [5 7 8]]
